version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"  # Or your desired Python version
  commands:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p /home/conda
    - export PATH="/home/conda/bin:$PATH"
    - conda activate base
    - conda install -c conda-forge -c hallkjc01 xcast 
    - pip install -r docs/pre-requirements.txt  # Or your documentation requirements file
    - pip install -r docs/requirements.txt  # Or your documentation requirements file
    - python -m sphinx -b html -d _build/doctrees docs _build/html


formats:
  - pdf
  - epub