version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"   
    
# Tell RTD to create the Conda env from the YAML above
conda:
  environment: docs/env.yml       # required for RTD schema; Conda env still rules

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub


