version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - bash -c "
        export PATH=$HOME/miniconda/bin:$PATH &&
        source $HOME/miniconda/etc/profile.d/conda.sh &&
        conda env create -f docs/WAS_S2S_linux.yml &&
        conda activate WASS2S &&
        pip install -r docs/requirements.txt
      "

sphinx:
  configuration: docs/source/conf.py

formats: 
  - pdf
