version: 2

build:
  os: ubuntu-22.04

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub

# Tell RTD to create the Conda env from the YAML above
conda:
  environment: docs/env.yml
