version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11" # Or your desired Python version
  commands:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    # Group all subsequent Conda operations within a single bash shell invocation
    # -e: exit immediately if a command exits with a non-zero status.
    # -c: read commands from the string.
    - bash -ec ' \
        echo "Setting PATH and sourcing conda.sh..."; \
        export PATH="$HOME/miniconda/bin:$PATH"; \
        source "$HOME/miniconda/etc/profile.d/conda.sh"; \
        \
        echo "Running conda init bash..."; \
        conda init bash; \
        \
        echo "Creating conda environment: WASS2S..."; \
        conda env create -f docs/WAS_S2S_linux.yml; \
        \
        echo "Activating conda environment: WASS2S..."; \
        conda activate WASS2S; \
        \
        echo "Installing pip requirements..."; \
        pip install -r docs/requirements.txt; \
        \
        echo "Building Sphinx documentation..."; \
        python -m sphinx -b html -d _build/doctrees docs _build/html \
      '

formats:
  - pdf
  - epub