version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - bash -c "
        export PATH=$HOME/miniconda/bin:$PATH &&
        source $HOME/miniconda/etc/profile.d/conda.sh &&
        conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main &&
        conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r &&
        conda env create -f docs/WAS_S2S_linux.yml &&
        conda activate WASS2S &&
        pip install -r docs/requirements.txt &&
        python -m sphinx -b html -d _build/doctrees docs/source $READTHEDOCS_OUTPUT/html &&
        rm -rf _build/latex/ &&
        python -m sphinx -b latex -d _build/doctrees docs/source _build/latex &&
        cd _build/latex &&
        pdflatex -interaction=nonstopmode *.tex &&
        pdflatex -interaction=nonstopmode *.tex &&
        mkdir -p $READTHEDOCS_OUTPUT/pdf &&
        rm -rf $READTHEDOCS_OUTPUT/pdf/*.pdf &&
        mv *.pdf $READTHEDOCS_OUTPUT/pdf/ &&
        cd ../..
      "

sphinx:
  configuration: docs/source/conf.py

formats: 
  - pdf
